
[functions]

[functions.create_admin_user]
verify_jwt = false

[functions.update_admin_password]
verify_jwt = false

[functions.delete_admin_user]
verify_jwt = false

[functions.create_drop_constraint_function]
verify_jwt = false

[functions.send-notification-email]
verify_jwt = false
